# TCL File Generated by Component Editor 20.1
# Sat Sep 28 18:19:19 AEST 2024
# DO NOT MODIFY


# 
# vga_face "vga_face" v1.0
#  2024.09.28.18:19:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_face
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_face
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_face
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_face
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_face.sv SYSTEM_VERILOG PATH vga_face.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_face
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_face.sv SYSTEM_VERILOG PATH vga_face.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 10
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data data Output 30
add_interface_port avalon_streaming_source endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source valid valid Output 1
add_interface_port avalon_streaming_source ready ready Input 1


# 
# connection point in_data
# 
add_interface in_data conduit end
set_interface_property in_data associatedClock clock
set_interface_property in_data associatedReset ""
set_interface_property in_data ENABLED true
set_interface_property in_data EXPORT_OF ""
set_interface_property in_data PORT_NAME_MAP ""
set_interface_property in_data CMSIS_SVD_VARIABLES ""
set_interface_property in_data SVD_ADDRESS_GROUP ""

add_interface_port in_data in_data in_data Input 12


# 
# connection point start_p
# 
add_interface start_p conduit end
set_interface_property start_p associatedClock clock
set_interface_property start_p associatedReset ""
set_interface_property start_p ENABLED true
set_interface_property start_p EXPORT_OF ""
set_interface_property start_p PORT_NAME_MAP ""
set_interface_property start_p CMSIS_SVD_VARIABLES ""
set_interface_property start_p SVD_ADDRESS_GROUP ""

add_interface_port start_p start_p start_p Input 1


# 
# connection point end_p
# 
add_interface end_p conduit end
set_interface_property end_p associatedClock clock
set_interface_property end_p associatedReset ""
set_interface_property end_p ENABLED true
set_interface_property end_p EXPORT_OF ""
set_interface_property end_p PORT_NAME_MAP ""
set_interface_property end_p CMSIS_SVD_VARIABLES ""
set_interface_property end_p SVD_ADDRESS_GROUP ""

add_interface_port end_p end_p end_p Input 1


# 
# connection point vga_ready
# 
add_interface vga_ready conduit end
set_interface_property vga_ready associatedClock clock
set_interface_property vga_ready associatedReset ""
set_interface_property vga_ready ENABLED true
set_interface_property vga_ready EXPORT_OF ""
set_interface_property vga_ready PORT_NAME_MAP ""
set_interface_property vga_ready CMSIS_SVD_VARIABLES ""
set_interface_property vga_ready SVD_ADDRESS_GROUP ""

add_interface_port vga_ready vga_ready vga_ready Output 1


# 
# connection point mic_en
# 
add_interface mic_en conduit end
set_interface_property mic_en associatedClock clock
set_interface_property mic_en associatedReset ""
set_interface_property mic_en ENABLED true
set_interface_property mic_en EXPORT_OF ""
set_interface_property mic_en PORT_NAME_MAP ""
set_interface_property mic_en CMSIS_SVD_VARIABLES ""
set_interface_property mic_en SVD_ADDRESS_GROUP ""

add_interface_port mic_en mic_en mic_en Input 1


# 
# connection point filter_mode
# 
add_interface filter_mode conduit end
set_interface_property filter_mode associatedClock clock
set_interface_property filter_mode associatedReset ""
set_interface_property filter_mode ENABLED true
set_interface_property filter_mode EXPORT_OF ""
set_interface_property filter_mode PORT_NAME_MAP ""
set_interface_property filter_mode CMSIS_SVD_VARIABLES ""
set_interface_property filter_mode SVD_ADDRESS_GROUP ""

add_interface_port filter_mode filter_mode filter_mode Input 3


# 
# connection point face_select
# 
add_interface face_select conduit end
set_interface_property face_select associatedClock clock
set_interface_property face_select associatedReset ""
set_interface_property face_select ENABLED true
set_interface_property face_select EXPORT_OF ""
set_interface_property face_select PORT_NAME_MAP ""
set_interface_property face_select CMSIS_SVD_VARIABLES ""
set_interface_property face_select SVD_ADDRESS_GROUP ""

add_interface_port face_select face_select face_select Input 2


# 
# connection point pitch
# 
add_interface pitch conduit end
set_interface_property pitch associatedClock clock
set_interface_property pitch associatedReset ""
set_interface_property pitch ENABLED true
set_interface_property pitch EXPORT_OF ""
set_interface_property pitch PORT_NAME_MAP ""
set_interface_property pitch CMSIS_SVD_VARIABLES ""
set_interface_property pitch SVD_ADDRESS_GROUP ""

add_interface_port pitch pitch pitch Input 20

