# TCL File Generated by Component Editor 20.1
# Fri Sep 27 15:27:23 AEST 2024
# DO NOT MODIFY


# 
# vga_face "vga_face" v1.0
#  2024.09.27.15:27:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_face
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_face
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_face
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_face
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_face.sv SYSTEM_VERILOG PATH vga_face.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_face
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_face.sv SYSTEM_VERILOG PATH vga_face.sv


# 
# parameters
# 
add_parameter W INTEGER 12
set_parameter_property W DEFAULT_VALUE 12
set_parameter_property W DISPLAY_NAME W
set_parameter_property W TYPE INTEGER
set_parameter_property W UNITS None
set_parameter_property W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property W HDL_PARAMETER true
add_parameter image_width INTEGER 320
set_parameter_property image_width DEFAULT_VALUE 320
set_parameter_property image_width DISPLAY_NAME image_width
set_parameter_property image_width TYPE INTEGER
set_parameter_property image_width UNITS None
set_parameter_property image_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property image_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 10
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data data Output 30
add_interface_port avalon_streaming_source endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source ready ready Input 1
add_interface_port avalon_streaming_source startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source valid valid Output 1


# 
# connection point filter_mode
# 
add_interface filter_mode conduit end
set_interface_property filter_mode associatedClock clock
set_interface_property filter_mode associatedReset ""
set_interface_property filter_mode ENABLED true
set_interface_property filter_mode EXPORT_OF ""
set_interface_property filter_mode PORT_NAME_MAP ""
set_interface_property filter_mode CMSIS_SVD_VARIABLES ""
set_interface_property filter_mode SVD_ADDRESS_GROUP ""

add_interface_port filter_mode filter_mode filter_mode Input 3


# 
# connection point x_ready
# 
add_interface x_ready conduit end
set_interface_property x_ready associatedClock clock
set_interface_property x_ready associatedReset ""
set_interface_property x_ready ENABLED true
set_interface_property x_ready EXPORT_OF ""
set_interface_property x_ready PORT_NAME_MAP ""
set_interface_property x_ready CMSIS_SVD_VARIABLES ""
set_interface_property x_ready SVD_ADDRESS_GROUP ""

add_interface_port x_ready x_ready x_ready Output 1

